# Run the Abot Rasa model/channel server
FROM rasa/rasa:3.4.5

ENV RASA_ACTION_ENDPOINT=http://localhost:5055/webhook

WORKDIR /app

COPY . /app

# Install packages
# TODO: Is there any other way to install without being root?
USER root
RUN pip install -q -r requirements.rasa.txt
USER 1001
