# Run the Abot Rasa Actions server
FROM rasa/rasa-sdk:3.4.1

ENV BACKEND_ENDPOINT_BASE=$BACKEND_ENDPOINT_BASE

USER root

WORKDIR /app
COPY ./requirements.actions.txt /app/requirements.actions.txt
RUN pip install -q --no-cache-dir --upgrade -r /app/requirements.actions.txt

COPY . /app

# Don't use root user to run code
USER 1001
