# Run the Abot Rasa Actions server
FROM rasa/rasa-sdk:3.4.1

USER root

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

CMD ["rasa", "run", "actions"]
