# Run the Abot Rasa model/channel server
FROM rasa/rasa:3.4.5

ARG ENDPOINTS_FILE=endpoints.yml
ARG CREDENTIALS_FILE=credentials.yml

ENV RASA_ACTION_ENDPOINT=http://localhost:5055/webhook

WORKDIR /app

COPY . /app

# Install packages
# TODO: Is there any other way to install without being root?
USER root
RUN pip install -r requirements.rasa.txt
USER 1001

CMD ["run", "--endpoints", "endpoints.test.yml", "--credentials", "credentials.test.yml"]
